# Generated by Django 4.1.5 on 2024-02-29 23:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fips", models.IntegerField()),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "county",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "state",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tract_id", models.IntegerField()),
                ("name", models.CharField(max_length=128)),
                ("name_lsad", models.CharField(max_length=512)),
                ("mtfcc", models.CharField(max_length=128)),
                ("funcstat", models.CharField(max_length=64)),
                ("aland", models.BigIntegerField(blank=True, null=True)),
                ("awater", models.BigIntegerField(blank=True, null=True)),
                ("intptlat", models.FloatField(blank=True, null=True)),
                ("intptlon", models.FloatField(blank=True, null=True)),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.county"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.state"
                    ),
                ),
            ],
            options={
                "db_table": "tract",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="county",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.state"
            ),
        ),
    ]
