# Generated by Django 4.1.5 on 2024-03-01 00:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tract",
            name="shape",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
