# Generated by Django 4.1.5 on 2024-03-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinedStatisticalArea",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "csa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CoreBasedStatisticalArea",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "cbsa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CountyToCBSA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cbsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.corebasedstatisticalarea",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.county"
                    ),
                ),
            ],
            options={
                "db_table": "county_to_cbsa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CBSAToCSA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cbsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.corebasedstatisticalarea",
                    ),
                ),
                (
                    "csa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.combinedstatisticalarea",
                    ),
                ),
            ],
            options={
                "db_table": "cbsa_to_csa",
                "managed": True,
            },
        ),
    ]
