# Generated by Django 4.1.5 on 2024-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_combinedstatisticalarea_corebasedstatisticalarea_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="county",
            name="fips",
        ),
        migrations.RemoveField(
            model_name="tract",
            name="tract_id",
        ),
        migrations.AlterField(
            model_name="county",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tract",
            name="id",
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
