# Generated by Django 4.1.5 on 2024-03-01 01:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_tract_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tract",
            name="shape",
            field=django.contrib.gis.db.models.fields.PolygonField(
                geography=True, srid=4326
            ),
        ),
    ]
