# Generated by Django 4.1.5 on 2024-03-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_county_fips_remove_tract_tract_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countytocbsa",
            name="cbsa",
        ),
        migrations.RemoveField(
            model_name="countytocbsa",
            name="county",
        ),
        migrations.AddField(
            model_name="corebasedstatisticalarea",
            name="csa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.combinedstatisticalarea",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="cbsa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.corebasedstatisticalarea",
            ),
        ),
        migrations.DeleteModel(
            name="CBSAToCSA",
        ),
        migrations.DeleteModel(
            name="CountyToCBSA",
        ),
    ]
