# Generated by Django 4.1.5 on 2024-03-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_tract_shape"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACSVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acs_code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=1024)),
                ("concept", models.CharField(max_length=1024)),
                ("group", models.CharField(max_length=64)),
                ("required", models.BooleanField(default=False)),
                ("predicate_type", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "acs_variable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ACS5ValueByTract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "acs_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.acsvariable",
                    ),
                ),
                (
                    "tract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.tract"
                    ),
                ),
            ],
            options={
                "db_table": "acs5_value_by_tract",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ACS1ValueByTract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "acs_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.acsvariable",
                    ),
                ),
                (
                    "tract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.tract"
                    ),
                ),
            ],
            options={
                "db_table": "acs1_value_by_tract",
                "managed": True,
            },
        ),
    ]
