# Generated by Django 4.1.5 on 2024-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_acsvariable_acs5valuebytract_acs1valuebytract"),
    ]

    operations = [
        migrations.AddField(
            model_name="acs1valuebytract",
            name="value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="acs5valuebytract",
            name="value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
