# Generated by Django 4.1.5 on 2024-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_acs1valuebytract_value_acs5valuebytract_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acsvariable",
            name="id",
        ),
        migrations.AlterField(
            model_name="acsvariable",
            name="acs_code",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
