# Generated by Django 4.1.5 on 2024-03-15 00:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_corebasedstatisticalarea_corebasestatisticalarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tract",
            name="shape",
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326
            ),
        ),
    ]
